# Generated by Django 4.2.1 on 2023-06-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ocr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('employee', models.IntegerField()),
                ('sales_amount', models.IntegerField()),
                ('company_url', models.URLField()),
                ('listed', models.CharField(max_length=10)),
                ('work_time', models.CharField(max_length=100)),
                ('work_hours', models.IntegerField()),
                ('over_time', models.IntegerField()),
                ('basic_salary', models.IntegerField()),
                ('bonus_salary', models.IntegerField()),
                ('holiday', models.IntegerField()),
                ('on_site', models.BooleanField(choices=[(False, '無し'), (True, '有り')], default=False, help_text='客先常駐有=TRUE')),
            ],
        ),
    ]
